version: '3.8'

services:
  app:
    build: 
      context: . 
      dockerfile: Dockerfiles/app/Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - ./memo:/mnt
    depends_on:
      - db
  
  db:
    build: ./Dockerfiles/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
