services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
      target: 'develop-stage'
    ports: 
      - "8088:8088"
    volumes:
      - ./back:/src/back
    depends_on:
      - db
    # networks:
      # - default
      # - custom
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      # target: 'develop-stage'
    command: npm run dev
    ports:
      - '5173:5173'
    volumes:
      - ./front:/src/front
    # networks:
    #   - custom
  
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    # networks:
    #   - custom

volumes:
  db-data:
  cargo-cache:
  target-cache:
# networks:
#   custom:
#     external: true
