[package]
name = "memo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="4"
actix-rt = "2"
sqlx = { version = "0.5", features = ["postgres", "runtime-actix-rust-tls"] }
dotenv = "0.15"